package services

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ymedlop/kuberoutectl/internal/cache/jsonstore"
	"github.com/ymedlop/kuberoutectl/internal/domain"
	"github.com/ymedlop/kuberoutectl/internal/providers"
)

// preUpgradeStore copies the checked-in fixture into a temp cache dir and
// returns a store over it.
//
// The fixture is hand-written in the shape kuberoutectl produced BEFORE
// Target.CredentialIDs and Selection.CredentialID existed. It must never be
// regenerated by the current code — a fixture written by the code under test
// proves nothing about the format that code has to keep reading. If a change
// makes this test fail, that is a migration requirement, not a stale fixture.
func preUpgradeStore(t *testing.T) *jsonstore.Store {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "pre-upgrade-snapshot.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if strings.Contains(string(data), "credential_ids") {
		t.Fatal("the pre-upgrade fixture contains credential_ids; it has been regenerated and no longer tests anything")
	}
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "snapshot.json"), data, 0o600); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}
	return jsonstore.New(dir, dir)
}

// Edge case 8: a cache written before this feature must load and list exactly
// as it did, with no migration step.
func TestPreUpgradeSnapshot_LoadsAndLists(t *testing.T) {
	svc := NewTargetService(preUpgradeStore(t), nil)

	targets, err := svc.List(TargetFilter{})
	if err != nil {
		t.Fatalf("List: %v", err)
	}
	if len(targets) != 1 {
		t.Fatalf("got %d targets, want 1", len(targets))
	}
	if targets[0].CredentialIDs != nil {
		t.Errorf("CredentialIDs = %v, want nil — the field is absent from the fixture", targets[0].CredentialIDs)
	}
	if targets[0].CredentialID != "aws:prod-sso" {
		t.Errorf("CredentialID = %q, want it preserved", targets[0].CredentialID)
	}
	if targets[0].Alias == "" {
		t.Error("alias assignment must still work on a pre-upgrade snapshot")
	}
}

// The credential join must treat "no CredentialIDs" as "the one in
// CredentialID", which is what makes absent-means-primary work without a
// migration.
func TestPreUpgradeSnapshot_CredentialJoinFallsBackToTheSingleID(t *testing.T) {
	svc := NewTargetService(preUpgradeStore(t), nil)

	got, err := svc.ResolveWithCredentials("eks-prod-frankfurt")
	if err != nil {
		t.Fatalf("ResolveWithCredentials: %v", err)
	}
	if len(got.Credentials) != 1 || got.Credentials[0].Name != "prod-sso" {
		t.Fatalf("Credentials = %+v, want just prod-sso", got.Credentials)
	}
}

// A pre-upgrade cache must still activate. The selection written afterwards
// carries the credential, so the upgrade is one-way and needs no backfill.
func TestPreUpgradeSnapshot_StillActivates(t *testing.T) {
	store := preUpgradeStore(t)
	prov := &credentialActivatableProvider{activatableProvider: activatableProvider{id: "aws", canSwitch: true}}
	reg := providers.NewRegistry()
	if err := reg.Register(prov); err != nil {
		t.Fatalf("register: %v", err)
	}
	svc := NewSelectionService(store, reg, fixedNow)

	res, err := svc.UseTarget(context.Background(), "eks-prod-frankfurt", UseTargetOptions{Activate: true})
	if err != nil {
		t.Fatalf("UseTarget: %v", err)
	}
	if res.Credential.ID != "aws:prod-sso" {
		t.Errorf("credential = %q, want aws:prod-sso", res.Credential.ID)
	}
	if prov.activated == nil {
		t.Fatal("activation did not happen")
	}
	sel, err := store.LoadSelection()
	if err != nil {
		t.Fatalf("LoadSelection: %v", err)
	}
	if sel.CredentialID != "aws:prod-sso" {
		t.Errorf("persisted credential = %q, want it recorded going forward", sel.CredentialID)
	}
}

// A selection written before Selection.CredentialID existed decodes to empty,
// which resolves as "the default" rather than as a missing credential.
func TestPreUpgradeSelection_ResolvesAsDefault(t *testing.T) {
	store := preUpgradeStore(t)
	if err := store.SaveSelection(domain.Selection{
		TargetID: "arn:aws:eks:eu-central-1:111111111111:cluster/eks-prod-frankfurt",
	}); err != nil {
		t.Fatalf("SaveSelection: %v", err)
	}
	svc := NewSelectionService(store, providers.NewRegistry(), fixedNow)

	st, err := svc.Status()
	if err != nil {
		t.Fatalf("Status: %v", err)
	}
	if st.CredentialMissing {
		t.Error("an absent credential_id must not be reported as a vanished credential")
	}
	if st.Credential != nil {
		t.Errorf("Credential = %+v, want nil when the selection records none", st.Credential)
	}
}
